name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0
    - name: Run Build and Test using Nuke
      run: ./build.sh -Target Test -Configuration Release
