name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: Build And Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        # pulls all commits        
        fetch-depth: "0"
      # pulls all tags
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run Build and Test using Nuke
      run: ./build.ps1 -Target Test -Configuration Release -Verbosity Verbose
