name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: Build And Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    # Additional fetch to get all commits and tags
    - run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run Build and Test using Nuke
      run: ./build.ps1 -Target Test -Configuration Release --nuget_api_key ${{ secrets.NUGET_API_KEY }} --gh_api_key ${{ secrets.GITHUB_API_KEY }}
