name: "Build"

on: [push, pull_request]

jobs:
  build:
    name: Build And Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run Build and Test using Nuke
      run: ./build.ps1 -Target Test -Configuration Release
