name: "Release"

on:
  push:
    tags:
      - v**.**.** # Semantic Versioning like "v11.22.33"

jobs:
  publish:
    name: Build And Test And Publish
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Run Publish using Nuke
      run: ./build.ps1 -Target Publish -Configuration Release
